In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3,4,5,"hello"]    #list
a

[1, 2, 3, 4, 5, 'hello']

In [8]:
np.array(a)     #it will convert it in a string in the data type is mixed

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [9]:
l = [[1,2,3], [4,5,6], [7,8,9]]   #one dimensional list
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)          # arrays give two dimension space matrices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array generation function

In [13]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros((6,6))         # 6 rows and 6 coloums
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# LINSPACE

In [22]:
arr = np.linspace(1,5,3)    # no. of elements is 3 between 1 to 5 in the output
arr

array([1., 3., 5.])

In [23]:
arr = np.linspace(1,10,3)  
arr

array([ 1. ,  5.5, 10. ])

In [24]:
arr = np.linspace(1,5,7)    # no. of elements is 7 between 1 to 5 in the output
arr

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

# Random Generation Function

In [25]:
np.random.rand(10)        # will give random numbers between 0 to 1

array([0.55231341, 0.68986961, 0.22288714, 0.0646467 , 0.25539508,
       0.80415067, 0.11846735, 0.32544898, 0.95322661, 0.62233165])

In [26]:
np.random.randn(10)      # will give random number between -3 to 3 

array([-1.07331559, -0.43746155,  0.65516366, -0.45917443,  0.62942098,
        1.29076601, -0.4760131 ,  1.18611968, -2.76973971,  0.24292042])

In [27]:
np.random.randint(10,20,7)    # will give 7 integers between 10 to 20

array([15, 11, 11, 13, 13, 19, 14])

# Array Attributes

In [28]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape         #SHAPE

(3, 3)

In [30]:
arr.size    #SIZE

9

In [31]:
arr.dtype     #data type

dtype('int64')

# Array Methods

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.min()

1

In [39]:
arr.max()

9

In [40]:
arr.sum()    # sum of all elements in the matrices

45

In [41]:
np.sum(arr,axis = 0)       # axis =0 gives sum of colmns 

array([12, 15, 18])

In [42]:
np.sum(arr, axis =1 )      # axis =1 gives sum of rows

array([ 6, 15, 24])

In [43]:
arr.mean()     # middle element

5.0

In [44]:
arr.std()

2.581988897471611

In [45]:
arr.argmax()              # index of the max element i..e.. 9

8

# Reshaping And Resizing

In [46]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])