In [1]:
import numpy as np

# ARRAY OPERATIONS
 ARITHEMATIC OPERATIONS

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [4]:
arr2 = a1 + a2       # same way mul,div n subtract, power(**)
arr2

array([ 7,  9, 11, 13, 15])

# BROADCASTING

In [5]:
L = [10,20,30,40]
arr = np.array(L)

In [6]:
arr + 10

array([20, 30, 40, 50])

In [7]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
arr1 * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

# DEEP AND SHALLOW COPY
1 -- SHALLOW COPY

In [11]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice = a[:5]
slice = slice*10   # in shallow copy we make changes in sliced portion but it wont affect the original array
slice

array([10, 20, 30, 40, 50])

In [13]:
a          # no changes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

2 -- DEEP COPY

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
b = a
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX MULTIPLICATION

In [18]:
a = np.arange(1,5).reshape(2,2)
b =np.arange(5,9).reshape(2,2
                         )

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
b

array([[5, 6],
       [7, 8]])

In [21]:
a @ b      # matrix multi

array([[19, 22],
       [43, 50]])

In [22]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

-- transpose

In [23]:
a.T

array([[1, 3],
       [2, 4]])

In [24]:
b.T

array([[5, 7],
       [6, 8]])

# Advance array manipulation 

1 -- stacking array (we cannot stack two matrices that's why we use arrays)

In [25]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [26]:
np.vstack((a,b))       # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
np.hstack((a,b))        # horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

2 -- splitting array

In [29]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a = np.vsplit(c,2)         #vertical split
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [34]:
b = np.hsplit(c,4)        # horizontal spilt of matrices
b

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [35]:
for i in b:
    print(i)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
