# Numpy indexing and slicing of vectors

In [2]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[4]             # indexing

15

In [5]:
arr[1:5]       # slicing

array([12, 13, 14, 15])

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

# Numpy indexing and slicing of matrices

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[5]

array([26, 27, 28, 29, 30])

In [13]:
arr[5,4]

30

In [14]:
arr[0,3]

4

In [16]:
slice = arr[1:3,1:4]
slice

array([[ 7,  8,  9],
       [12, 13, 14]])

In [18]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
arr[:,2]      # for selecting row

array([ 3,  8, 13, 18, 23, 28])

# BOOLEAN INDEXING 

In [20]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr%2==0          # extracting even numbers in the array
arr[bool_index]
arr

array([12, 14, 16, 18, 20])